version: "2"
services:
  app:
    build: .

    # env_file: .env
    # environment:
      # RAILS_ENV: $RAILS_ENV
      # - REDIS_URL=redis://redis:6998/0

    links:
      - db
      - redis
      # - node
    expose:
      - "3000"
    volumes:
      - .:/var/www/apiwoods

  db:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_USER=camellia
      - POSTGRES_PASSWORD=rR5qgoGnFzJ4B7yZ
    ports:
      - "6999:5432"
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.0.7-alpine
    expose:
      - "6379"
    volumes:
      - ./data-redis:/data

  node:
    build:
      context: .
      dockerfile: config/containers/node/Dockerfile
    # volumes:
    #   - node_modules
    volumes:
      - .:/var/www/apiwoods
    # volumes_from:
    #   - app

  web:
    build:
      context: .
      dockerfile: config/containers/nginx/Dockerfile

    links:
      - app

    ports:
      - "80:80"
    volumes_from:
      - app

# volumes:
#   node_modules: