# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a6f7de0f3404d796e3dac203d6d6e5978e100a6207c7ab3dc15a58cb65d695fd2aedda41c5165dc50f4b7643fd0a14483a11bec106b0ce3386b4f5f20b4d73

test:
  secret_key_base: 7d3701e90e907cd39c882ac98f334a01e221f04b261557768e7037f3f261f48088f98033dc84288a8ca5ceb4a8e65cc77e6f3fe76d03952326cd2eee8bb70da8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
